-- MySQL Script generated by MySQL Workbench
-- Mon Mar 31 18:20:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RestaurantMS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RestaurantMS` ;

-- -----------------------------------------------------
-- Schema RestaurantMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RestaurantMS` DEFAULT CHARACTER SET utf8 ;
USE `RestaurantMS` ;

-- -----------------------------------------------------
-- Table `RestaurantMS`.`Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RestaurantMS`.`Manager` ;

CREATE TABLE IF NOT EXISTS `RestaurantMS`.`Manager` (
  `ManagerID` INT NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Tel` VARCHAR(45) NULL,
  `ManagerName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ManagerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantMS`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RestaurantMS`.`Employee` ;

CREATE TABLE IF NOT EXISTS `RestaurantMS`.`Employee` (
  `EmployeeID` INT NOT NULL,
  `EmployeeName` VARCHAR(45) NOT NULL,
  `Salary` INT NULL,
  `Position` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Tel` VARCHAR(45) NULL,
  `SupervisorID` INT NULL,
  PRIMARY KEY (`EmployeeID`),
  INDEX `SupervisorID_idx` (`SupervisorID` ASC) VISIBLE,
  CONSTRAINT `SupervisorID`
    FOREIGN KEY (`SupervisorID`)
    REFERENCES `RestaurantMS`.`Manager` (`ManagerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantMS`.`MenuItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RestaurantMS`.`MenuItem` ;

CREATE TABLE IF NOT EXISTS `RestaurantMS`.`MenuItem` (
  `MenuItemID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Available` TINYINT NOT NULL,
  PRIMARY KEY (`MenuItemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantMS`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RestaurantMS`.`Orders` ;

CREATE TABLE IF NOT EXISTS `RestaurantMS`.`Orders` (
  `OrderDate` DATE NOT NULL,
  `OrderID` INT NOT NULL,
  `Customer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OrderID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantMS`.`OrderMenuItemCooker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RestaurantMS`.`OrderMenuItemCooker` ;

CREATE TABLE IF NOT EXISTS `RestaurantMS`.`OrderMenuItemCooker` (
  `OrderID` INT NOT NULL,
  `CookerID` INT NOT NULL,
  `MenuItemID` INT NOT NULL,
  INDEX `CookerID_idx` (`CookerID` ASC) VISIBLE,
  INDEX `MenuItemID_idx` (`MenuItemID` ASC) VISIBLE,
  PRIMARY KEY (`OrderID`, `CookerID`, `MenuItemID`),
  CONSTRAINT `OrderID`
    FOREIGN KEY (`OrderID`)
    REFERENCES `RestaurantMS`.`Orders` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CookerID`
    FOREIGN KEY (`CookerID`)
    REFERENCES `RestaurantMS`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MenuItemID`
    FOREIGN KEY (`MenuItemID`)
    REFERENCES `RestaurantMS`.`MenuItem` (`MenuItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `RestaurantMS` ;

-- -----------------------------------------------------
-- Placeholder table for view `RestaurantMS`.`ChefDishesView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestaurantMS`.`ChefDishesView` (`EmployeeID` INT, `ChefName` INT, `MenuItemID` INT, `DishName` INT, `Price` INT, `TimesCooked` INT, `Customers` INT);

-- -----------------------------------------------------
-- View `RestaurantMS`.`ChefDishesView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RestaurantMS`.`ChefDishesView`;
DROP VIEW IF EXISTS `RestaurantMS`.`ChefDishesView` ;
USE `RestaurantMS`;
-- 创建视图：厨师及其制作的菜品
CREATE  OR REPLACE VIEW ChefDishesView AS
SELECT 
    e.EmployeeID,
    e.EmployeeName AS ChefName,
    mi.MenuItemID,
    mi.Name AS DishName,
    mi.Price,
    COUNT(omc.OrderID) AS TimesCooked,
    GROUP_CONCAT(DISTINCT o.Customer) AS Customers
FROM Employee e
JOIN OrderMenuItemCooker omc ON e.EmployeeID = omc.CookerID
JOIN MenuItem mi ON omc.MenuItemID = mi.MenuItemID
JOIN Orders o ON omc.OrderID = o.OrderID
WHERE e.Position = 'COOKER'
GROUP BY e.EmployeeID, mi.MenuItemID;
USE `RestaurantMS`;

DELIMITER $$

USE `RestaurantMS`$$
DROP TRIGGER IF EXISTS `RestaurantMS`.`CheckCookerPositionT` $$
USE `RestaurantMS`$$
CREATE TRIGGER `CheckCookerPositionT` 
BEFORE INSERT ON `OrderMenuItemCooker` 
FOR EACH ROW 
BEGIN
    DECLARE employee_position VARCHAR(45);

    -- 获取 CookerID 对应的职位
    SELECT Position 
    INTO employee_position
    FROM Employee 
    WHERE EmployeeID = NEW.CookerID
    LIMIT 1;

    -- 检查职位是否为 'COOKER'
    IF employee_position IS NULL OR employee_position != 'COOKER' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'CookerID must reference an employee with position COOKER';
    END IF;
END;$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
